# Day1 Pytorch基础
赵晓冬 2019.8.10

In [1]:
import torch

In [2]:
x = torch.ones(3, 5)

In [3]:
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [4]:
x = x.cuda()

In [5]:
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')


In [6]:
x.reshape(5, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

## 练习1：swap two row of a tensor

In [7]:
x = torch.arange(9).reshape(3, 3)

In [8]:
print(x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [9]:
# swap row0 and row2
x = x[[2, 1, 0]]

In [10]:
print(x)

tensor([[6, 7, 8],
        [3, 4, 5],
        [0, 1, 2]])


## 练习2：extract all 3x3 block from 10x10 tensor

In [11]:
x = torch.arange(100).reshape(10, 10)

In [12]:
print(x)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])


In [13]:
res2 = torch.stack([torch.stack([x.narrow(0, i, 3).narrow(1, j, 3) for j in range(0, 8)]) for i in range(0, 8)])

In [14]:
print(res2)

tensor([[[[ 0,  1,  2],
          [10, 11, 12],
          [20, 21, 22]],

         [[ 1,  2,  3],
          [11, 12, 13],
          [21, 22, 23]],

         [[ 2,  3,  4],
          [12, 13, 14],
          [22, 23, 24]],

         [[ 3,  4,  5],
          [13, 14, 15],
          [23, 24, 25]],

         [[ 4,  5,  6],
          [14, 15, 16],
          [24, 25, 26]],

         [[ 5,  6,  7],
          [15, 16, 17],
          [25, 26, 27]],

         [[ 6,  7,  8],
          [16, 17, 18],
          [26, 27, 28]],

         [[ 7,  8,  9],
          [17, 18, 19],
          [27, 28, 29]]],


        [[[10, 11, 12],
          [20, 21, 22],
          [30, 31, 32]],

         [[11, 12, 13],
          [21, 22, 23],
          [31, 32, 33]],

         [[12, 13, 14],
          [22, 23, 24],
          [32, 33, 34]],

         [[13, 14, 15],
          [23, 24, 25],
          [33, 34, 35]],

         [[14, 15, 16],
          [24, 25, 26],
          [34, 35, 36]],

         [[15, 16, 17],
          [2

In [15]:
print(res2.shape)

torch.Size([8, 8, 3, 3])


# 练习3：for 10x3 tensor, extract rows without repeated values

In [16]:
a = torch.randint(0, 6, (10, 3))

In [17]:
print(a)

tensor([[2, 2, 0],
        [2, 2, 2],
        [3, 0, 0],
        [3, 1, 1],
        [3, 2, 4],
        [4, 5, 0],
        [1, 5, 0],
        [5, 5, 3],
        [2, 5, 3],
        [5, 1, 5]])


In [18]:
idx = [len(row.unique()) == len(row) for row in a]

In [19]:
a[idx]

tensor([[3, 2, 4],
        [4, 5, 0],
        [1, 5, 0],
        [2, 5, 3]])